export const dragTablesList = [
  {
    typeId: "1",
    title: "Стол на 5 мест",
    image: "/img/tables/table_1.png",
    width: 120,
    height: 120,
  },
  {
    typeId: "2",
    title: "Стол на 5 мест",
    image: "/img/tables/table_2.png",
    width: 120,
    height: 120,
  },
  {
    typeId: "3",
    title: "Стол на 5 мест",
    image: "/img/tables/table_3.png",
    width: 120,
    height: 120,
  },
  {
    typeId: "4",
    title: "Стол на 5 мест",
    image: "/img/tables/table_4.png",
    width: 120,
    height: 120,
  },
  {
    typeId: "5",
    title: "Стол круглый на 4 места",
    image: "/img/tables/table_5.png",
    width: 120,
    height: 120,
  },
  {
    typeId: "6",
    title: "Стол у стены на 2 места",
    image: "/img/tables/table_6.png",
    width: 55,
    height: 120,
  },
  {
    typeId: "7",
    title: "Диван левая часть",
    image: "/img/tables/table_7.png",
    width: 67,
    height: 120,
  },
  {
    typeId: "8",
    title: "Диван средняя часть",
    image: "/img/tables/table_8.png",
    width: 60,
    height: 120,
  },
  {
    typeId: "9",
    title: "Диван правая часть",
    image: "/img/tables/table_9.png",
    width: 70,
    height: 120,
  },
  {
    typeId: "10",
    title: "Диван левая часть",
    image: "/img/tables/table_10.png",
    width: 73,
    height: 120,
  },
  {
    typeId: "11",
    title: "Диван правая часть",
    image: "/img/tables/table_11.png",
    width: 73,
    height: 120,
  },
];
