export const ADD_DRAG_ITEM = "ADD_DRAG_ITEM";
export const MOVE_DRAG_ITEM = "MOVE_DRAG_ITEM";
export const SELECT_DRAG_ITEM = "SELECT_DRAG_ITEM";
export const DELETE_SELECT_DRAG_ITEM = "DELETE_SELECT_DRAG_ITEM";
export const DELETE_ALL_DRAG_ITEMS = "DELETE_ALL_DRAG_ITEMS";
export const ADD_MULTI_DRAG_ITEMS = "ADD_MULTI_DRAG_ITEMS";
